export const UPDATE_BOOKIN_FIELD = 'UPDATE_BOOKIN_FIELD';
export const RESET_BOOKIN_STATE = 'RESET_BOOKIN_STATE';
export const VALIDATE_BOOKIN_FIELDS = 'VALIDATE_BOOKIN_FIELDS';
export const BOOKIN_FORM_UNLOADED = 'BOOKIN_FORM_UNLOADED';
export const CLEAR_BOOKIN_ERROR = 'CLEAR_BOOKIN_ERROR';

export const ADD_COURTESY_IPHONE = 'ADD_COURTESY_IPHONE';
export const ADD_COURTESY_OTHER = 'ADD_COURTESY_OTHER';
export const ADD_COURTESY_CHARGER = 'ADD_COURTESY_CHARGER';
export const REMOVED_COURTESY_LINE_ITEM = 'REMOVED_COURTESY_LINE_ITEM';

export const UPDATE_FAQ_SEARCH_FIELD = 'UPDATE_FAQ_SEARCH_FIELD';
export const LOAD_FAQ_DATA = 'LOAD_FAQ_DATA';

export const LOAD_STORE_LOCATIONS = 'LOAD_STORE_LOCATIONS';