export const UPDATE_BOOKIN_FIELD = 'UPDATE_BOOKIN_FIELD';
export const RESET_BOOKIN_STATE = 'RESET_BOOKIN_STATE';

export const ADD_COURTESY_IPHONE = 'ADD_COURTESY_IPHONE';
export const ADD_COURTESY_OTHER = 'ADD_COURTESY_OTHER';
export const ADD_COURTESY_CHARGER = 'ADD_COURTESY_CHARGER';
export const REMOVED_COURTESY_LINE_ITEM = 'REMOVED_COURTESY_LINE_ITEM';